// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in a Magnetometer data packet<br>
 *
 * The magnetometer data is measured on 3 axes as shown in the picture below:
 * \image html MuseAxes.png
 *
 * The axes are oriented to a Right Hand Coordinate System.<br>
 * TODO: fill in details about how magnetometer work
 * \sa \enumlink{MuseDataPacketType,MAGNETOMETER,IXNMuseDataPacketTypeMagnetometer}
 * \sa \functionlink{MuseDataPacket,getMagnetometerValue,get_magnetometer_value}
 */
typedef NS_ENUM(NSInteger, IXNMagnetometer)
{
    IXNMagnetometerX,
    IXNMagnetometerY,
    IXNMagnetometerZ,
};
