// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from museinfo.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * The model identifier of the headbands.  The model is laser printed on the
 *  inside of the left pod of the headband as either "MU-01", "MU-02" or "MU-03".
 * \muse2019 and \muse2021 models are marked on the underside as "MS-01" or "MS-02".
 */
typedef NS_ENUM(NSInteger, IXNMuseModel)
{
    /** First model of Muse, Muse 2014 */
    IXNMuseModelMu01,
    /** Muse 2016 with Bluetooth Low Energy support. */
    IXNMuseModelMu02,
    /** Muse2 2018 adding PPG sensor, Accelerometer and Gyroscope. */
    IXNMuseModelMu03,
    /** MuseS 2019 softband. */
    IXNMuseModelMu04,
    /** MuseS 2021 softband refresh. */
    IXNMuseModelMu05,
};
