// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in a Pressure packet.
 * \sa \enumlink{MuseDataPacketType,PRESSURE,IXNMuseDataPacketTypePressure}
 * \sa \functionlink{MuseDataPacket,getPressureValue,get_pressure_value}
 */
typedef NS_ENUM(NSInteger, IXNPressure)
{
    /** The raw pressure value returned by the pressure sensor in mBar */
    IXNPressureRaw,
    /**
     * The averaged pressure value in mBar based on the last 10 readings.  This
     * provides a smoother curve for the pressure values.
     */
    IXNPressureAveraged,
};
