// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in a PPG packet.
 * Enum values for IR and RED correspond to the Infrared and Red values.
 * The AMBIENT enum value is repurposed on models after \muse2018.
 * <br/>
 * \n \muse2018 AMBIENT represents the Ambient value.
 * \n \muse2019 AMBIENT represents the Green value. There is no Ambient available and Red is not used.
 * \n \muse2021 AMBIENT represents the IR-H16 value. There is no Ambient available.
 *
 * Raw PPG values are given in microamps.
 *
 * \sa \enumlink{MuseDataPacketType,PPG,IXNMuseDataPacketTypePpg}
 * \sa \functionlink{MuseDataPacket,getPpgChannelValue,get_ppg_channel_value}
 */
typedef NS_ENUM(NSInteger, IXNPpg)
{
    /** Ambient, Green or IR-H16. */
    IXNPpgAMBIENT,
    /** IR. */
    IXNPpgIR,
    /** Red. */
    IXNPpgRED,
};
